export const FETCHING_CONTESTS = 'FETCHING_CONTEST'
export const FETCH_CONTESTS_SUCCESS = 'FETCH_CONTEST_SUCCESS'
export const FETCH_CONTESTS_ERROR = 'FETCH_CONTEST_ERROR'

export const FETCH_USER = 'FETCH_USER'
